### ISSUE TITLE
Compatibilidade com magento 2.4.4

### ISSUE THREAD

**Issue by LeoNun** [ifthenpay/magento2#2]
Boa tarde,
venho por este meio saber se existe previsão de quando sairá uma versão compativel com o Magento 2.4.4 e consequentemente PHP8.1?
Já alguém testou para ver se funcionou com esta versão?

Cumprimentos,
L. Nunes

**Comment by josesoaresif** [comment]
Sim, testado em Magento 2.4.5 com PHP 8.1 e funciona corretamente com a última versão (no momento deste issue v1.2.11). Foi necessário alargar a permissão de dependência de PHP no composer.

**Comment by LeoNun** [comment]
Boa tarde, sim, já confirmei que sim, esqueci-me de comunicar.

Cumprimentos,
L. Nunes
