### ISSUE TITLE
Compatibilidade com magento 2.4.6

### ISSUE THREAD

**Issue by diogobox** [ifthenpay/magento2#3]
Boa tarde,
venho por este meio saber se existe previsão de quando sairá uma versão compativel com o Magento 2.4.6?
Já alguém testou para ver se funcionou com esta versão?

Cumprimentos

**Comment by LeoNun** [comment]
Bom dia,
sim, está instalado na versão 2.46-p2 e a funcionar, existe apenas um problema ao efetuar o Di Compile que não finaliza, o seguinte erro aparece no log:

PHP Fatal error:  Class Ifthenpay\Payment\Model\MbwayRepository contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Ifthenpay\Payment\Api\MbwayRepositoryInterface::getByTransactionId) in /public_html/app/code/Ifthenpay/Payment/Model/MbwayRepository.php on line 10


Com os melhores cumprimentos,
Leonel Nunes

**Comment by LeoNun** [comment]
Bom dia novamente,
para resolver o problema basta colocar abstract no inicio da linha 10 dos ficheiros:

CCardRepository.php
MbwayRepository.php
MultibancoRepository.php
PayshopRepository.php

Com os melhores cumprimentos,
Leonel Nunes

**Comment by LeoNun** [comment]
Boa tarde,
ainda relativamente à ultima versão disponivel e a compatibilidade com a versão 2.4.6-p2.
Encontrei um grave problema, pois apesar de este aparentemente funcionar bem, e não encontrei problema diretamente nestes, os outros métodos de envio do magento, como cash on delivery, bank transfer ou Paypal, após um destes ser selecionado e finalizada a encomenda, a página success apresenta o seguinte erro:

1 exception(s):
Exception #0 (Exception): Unknown Config Class

Exception #0 (Exception): Unknown Config Class
<pre>#1 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#2 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#3 Magento\Framework\ObjectManager\ObjectManager->create() called at [vendor/magento/framework/View/Element/BlockFactory.php:44]
#4 Magento\Framework\View\Element\BlockFactory->createBlock() called at [vendor/magento/framework/View/Layout/Generator/Block.php:272]
#5 Magento\Framework\View\Layout\Generator\Block->getBlockInstance() called at [vendor/magento/framework/View/Layout/Generator/Block.php:252]
#6 Magento\Framework\View\Layout\Generator\Block->createBlock() called at [vendor/magento/framework/View/Layout/Generator/Block.php:229]
#7 Magento\Framework\View\Layout\Generator\Block->generateBlock() called at [vendor/magento/framework/View/Layout/Generator/Block.php:134]
#8 Magento\Framework\View\Layout\Generator\Block->process() called at [vendor/magento/framework/View/Layout/GeneratorPool.php:93]
#9 Magento\Framework\View\Layout\GeneratorPool->process() called at [vendor/magento/framework/View/Layout.php:365]
#10 Magento\Framework\View\Layout->generateElements() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#11 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#12 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#13 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:32]
#14 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#15 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:65]
#16 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#17 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:271]
#18 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:896]
#19 Magento\Framework\View\Layout->getBlock() called at [vendor/magento/module-google-analytics/Observer/SetGoogleAnalyticsOnOrderSuccessPageViewObserver.php:61]
#20 Magento\GoogleAnalytics\Observer\SetGoogleAnalyticsOnOrderSuccessPageViewObserver->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:88]
#21 Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:74]
#22 Magento\Framework\Event\Invoker\InvokerDefault->dispatch() called at [vendor/magento/framework/Event/Manager.php:65]
#23 Magento\Framework\Event\Manager->dispatch() called at [generated/code/Magento/Framework/Event/Manager/Proxy.php:95]
#24 Magento\Framework\Event\Manager\Proxy->dispatch() called at [vendor/magento/module-checkout/Controller/Onepage/Success.php:33]
#25 Magento\Checkout\Controller\Onepage\Success->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#26 Magento\Checkout\Controller\Onepage\Success\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#27 Magento\Checkout\Controller\Onepage\Success\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#28 Magento\Checkout\Controller\Onepage\Success\Interceptor->___callPlugins() called at [generated/code/Magento/Checkout/Controller/Onepage/Success/Interceptor.php:23]
#29 Magento\Checkout\Controller\Onepage\Success\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#30 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-checkout/Controller/Onepage.php:161]
#31 Magento\Checkout\Controller\Onepage->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#32 Magento\Checkout\Controller\Onepage\Success\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#33 Magento\Checkout\Controller\Onepage\Success\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#34 Magento\Checkout\Controller\Onepage\Success\Interceptor->___callPlugins() called at [generated/code/Magento/Checkout/Controller/Onepage/Success/Interceptor.php:32]
#35 Magento\Checkout\Controller\Onepage\Success\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#36 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#37 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#38 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#39 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#40 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#41 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#42 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:75]
#43 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#44 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#45 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#46 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#47 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#48 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>

Desativei alguns modulos e cheguei à conclusão de que o problema era deste porque o erro não era concreto e o único erro que tenho nos logs do magento é no system.log com o seguinte:

[2023-09-05T16:22:36.719748+00:00] main.ERROR: Unknown Config Class [] []

Parece que afinal existe algo a fazer para a completa compatibilidade.

Com os melhores cumprimentos,
Leonel Nunes
